version: 2 
jobs: # basic units of work in a run
  unit-tests: 
  
    docker:
      - image:  cimg/go:1.18

    environment:
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    
    parallelism: 2

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Run unit tests
          # store the results of our tests in the $TEST_RESULTS directory
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results
  
  godog-tests:
    docker:
      - image: cimg/go:1.18

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: install godog
          command: go install github.com/cucumber/godog/cmd/godog@latest
      
      - run:
          name: run godog tests
          command: cd test && godog run


workflows:
  version: 2
  testing:
    jobs:
      - unit-tests
      - for-main-test:
          requires:
            - unit-tests
          filters:
            branches:
              only:
                - main

